# config/packages/prod/nelmio_cors.yaml
nelmio_cors:
    defaults:
        origin_regex: false
        allow_origin: ['https://secure-dev.vercel.app']
        allow_methods: ['GET', 'POST', 'OPTIONS']
        allow_headers: ['Content-Type', 'Authorization']
        max_age: 3600