services:
  - type: web
    name: securedev-backend
    runtime: docker
    env: php
    buildCommand: "./render-build.sh"
    startCommand: "php -d memory_limit=512M bin/console lexik:jwt:generate-keypair --skip-if-exists && php -d memory_limit=512M bin/console cache:warmup && symfony serve"
    envVars:
      - key: APP_ENV
        value: prod
      - key: APP_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: securedev-db
          property: connectionString