services:
  - type: web
    name: securedev-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn SecureDevBackend.wsgi
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: SecureDevBackend.settings
